Licentie: "LICENTIE-HIER"
KrijgHoeveelProcentTerugBijQuickSell: 80
#Dit kan bv de burgemeester zijn :)
GemeenteVerkoopSkullNaam: "ItsJust4You"
GemeenteVerkoopSkullUUID: "eff634b6-bcf2-4dc4-97c6-fd71033d282f"